django_cloud_panel_directory/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("user_account/settings", views.user_account_settings),
    path(
        "user_account/settings/change-profile-picture",
        views.modal_change_profile_picture,
    ),
    path("realms", views.list_realms),
    path("users", views.list_users),
    path("users/create", views.modal_users_create, name="modal_users_create"),
    path("user/<str:guid>", views.show_user),
    path("user/<str:guid>/reset-pw", views.modal_user_reset_pw),
    path("user/<str:guid>/delete", views.modal_user_delete, name="modal_user_delete"),
    path(
        "user/<str:guid>/groups",
        views.modal_user_manage_groups,
        name="modal_user_manage_groups",
    ),
    path("groups", views.list_groups),
    path("groups/create", views.modal_groups_create, name="modal_groups_create"),
    path("group/<str:group_guid>", views.show_group),
    path("group/<str:group_guid>/delete", views.modal_group_delete),
    path(
        "group/<str:group_guid>/members",
        views.modal_group_manage_members,
        name="modal_group_manage_members",
    ),
    path("computers", views.list_computers),
    path(
        "computers/create", views.modal_computers_create, name="modal_computers_create"
    ),
    path("computer/<str:guid>", views.show_computer),
    path("computer/<str:guid>/join-script", views.modal_computer_join_script),
    path("computer/<str:guid>/delete", views.modal_computer_delete),
    path(
        "computer/<str:guid>/groups",
        views.modal_computer_manage_groups,
        name="modal_computer_manage_groups",
    ),
    path("contacts", views.list_contacts),
    path("contacts/<int:contact_id>", views.show_contact),
]

django_cloud_panel_directory/forms.py
from braces.forms import UserKwargModelFormMixin
from django import forms
from django.utils.translation import gettext_lazy as _

from django_session_ldap_attributes.django_session_ldap_attributes.snippets import (
    get_mdat_customer_for_user,
)
from django_directory_backend_client.django_directory_backend_client.func import *


def get_computer_types():
    choices = list()

    for key, value in directory_backend_get_static_values()["computer_types"].items():
        choices.append((key, _(value)))

    return choices


def get_computer_countries():
    choices = list()

    for key, value in directory_backend_get_static_values()[
        "computer_countries"
    ].items():
        choices.append((key, _(value)))

    return choices


class DirectoryUserPasswordChangeForm(forms.Form):
    new_password = forms.CharField(
        label=_(""),
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "placeholder": "New Password (again)",
                "class": "form-control",
            }
        ),
        max_length=100,
    )
    new_password2 = forms.CharField(
        label=_(""),
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "placeholder": "Retype Password",
                "class": "form-control",
            }
        ),
        max_length=100,
    )


class DirectoryUserPasswordOwnChangeForm(forms.Form):
    old_password = forms.CharField(
        label=_(""),
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "Old Password",
            }
        ),
        max_length=100,
    )
    new_password = forms.CharField(
        label=_(""),
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "placeholder": "New Password",
                "class": "form-control",
            }
        ),
        max_length=100,
    )
    new_password2 = forms.CharField(
        label=_(""),
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "placeholder": "Retype Password",
                "class": "form-control",
            }
        ),
        max_length=100,
    )


class DirectoryUserDeleteForm(forms.Form):
    guid = forms.CharField(label=_("X-GUID"), widget=forms.HiddenInput, max_length=250)


class DirectoryUserCreateForm(UserKwargModelFormMixin, forms.Form):
    first_name = forms.CharField(
        label=_(""),
        widget=forms.TextInput(
            attrs={
                "class": "form-control col-lg-6",
                "placeholder": _("Firstname"),
                "onchange": "concat_names()",
            }
        ),
        required=False,
    )
    last_name = forms.CharField(
        label=_(""),
        widget=forms.TextInput(
            attrs={
                "class": "form-control col-lg-6",
                "placeholder": _("Lastname"),
                "onchange": "concat_names()",
            }
        ),
        required=False,
    )
    display_name = forms.CharField(
        label=_(""),
        widget=forms.TextInput(
            attrs={"class": "form-control col-lg-12", "placeholder": _("Display Name")}
        ),
        required=True,
    )
    username = forms.CharField(
        label=_(""),
        widget=forms.TextInput(
            attrs={"class": "form-control col-lg-6", "placeholder": _("Username")}
        ),
        required=True,
    )
    domain = forms.ChoiceField(
        label="", widget=forms.Select(attrs={"class": "form-control col-lg-5"})
    )

    def __init__(self, *args, **kwargs):
        super(DirectoryUserCreateForm, self).__init__(*args, **kwargs)

        # make sure, under no circumstances, user is None
        assert self.user is not None

        mdat = get_mdat_customer_for_user(self.user)

        domain_choices = list()

        domain_data = directory_backend_get_authdomain(mdat.id)

        for domain in domain_data:
            if domain["isDefault"]:
                self.initial["domain"] = domain["domain"]

            domain_choices.append((domain["domainID"], domain["domain"]))

        self.fields["domain"].choices = domain_choices


class DirectoryCreateGroupForm(forms.Form):
    group_name = forms.CharField(
        label=_(""),
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": _("New Group-name")}
        ),
        required=True,
    )


class DirectoryCreateComputerForm(forms.Form):
    type = forms.ChoiceField(
        choices=get_computer_types, widget=forms.Select(attrs={"class": "form-control"})
    )
    country = forms.ChoiceField(
        choices=get_computer_countries,
        widget=forms.Select(attrs={"class": "form-control"}),
    )


class DirectoryGroupMembersForm(UserKwargModelFormMixin, forms.Form):
    members = forms.MultipleChoiceField(
        required=False,
        widget=forms.SelectMultiple,
        label="",
    )

    def __init__(self, *args, **kwargs):
        self.group_attributes = kwargs.pop("group_attributes", None)

        super(DirectoryGroupMembersForm, self).__init__(*args, **kwargs)

        # make sure, under no circumstances, user is None
        assert self.user is not None

        mdat = get_mdat_customer_for_user(self.user)

        members_choices = list()
        members_selected = list()

        org_users = directory_backend_get_users(mdat.id)
        org_groups = directory_backend_get_groups(mdat.id)
        org_computers = directory_backend_get_computers(mdat.id)

        for org_user in org_users:
            members_choices.append(
                (
                    "user_" + org_user["objectGUID"][0],
                    _("User") + ": " + org_user["displayName"][0],
                )
            )
            if org_user["distinguishedName"][0].upper() in (
                dn.upper() for dn in self.group_attributes["member"]
            ):
                members_selected.append("user_" + org_user["objectGUID"][0])

        for org_group in org_groups:
            members_choices.append(
                (
                    "group_" + org_group["objectGUID"][0],
                    _("Group") + ": " + org_group["name"][0],
                )
            )
            if org_group["distinguishedName"][0].upper() in (
                dn.upper() for dn in self.group_attributes["member"]
            ):
                members_selected.append("group_" + org_group["objectGUID"][0])

        for org_computer in org_computers:
            members_choices.append(
                (
                    "computer_" + org_computer["objectGUID"][0],
                    _("Computer") + ": " + org_computer["name"][0],
                )
            )
            if org_computer["distinguishedName"][0].upper() in (
                dn.upper() for dn in self.group_attributes["member"]
            ):
                members_selected.append("computer_" + org_computer["objectGUID"][0])

        self.fields["members"].choices = members_choices
        self.fields["members"].initial = members_selected


class DirectoryUserGroupMembershipForm(UserKwargModelFormMixin, forms.Form):
    groups = forms.MultipleChoiceField(
        required=False,
        widget=forms.SelectMultiple,
        label="",
    )

    def __init__(self, *args, **kwargs):
        self.user_attributes = kwargs.pop("user_attributes", None)

        super(DirectoryUserGroupMembershipForm, self).__init__(*args, **kwargs)

        # make sure, under no circumstances, user is None
        assert self.user is not None

        mdat = get_mdat_customer_for_user(self.user)

        group_choices = list()
        group_selected = list()

        all_groups = directory_backend_get_groups(mdat.id)

        for group in all_groups:
            group_choices.append(f"group_{group['X-GUID']} : {group['name'][0]}")
            if group["distinguishedName"][0] in self.user_attributes["memberOf"]:
                group_selected.append(f"group_{group['X-GUID']}")

        self.fields["groups"].choices = group_choices
        self.fields["groups"].initial = group_selected


class DirectoryComputerGroupMembershipForm(UserKwargModelFormMixin, forms.Form):
    groups = forms.MultipleChoiceField(
        required=False,
        widget=forms.SelectMultiple,
        label="",
    )

    def __init__(self, *args, **kwargs):
        self.computer_attributes = kwargs.pop("computer_attributes", None)

        super(DirectoryComputerGroupMembershipForm, self).__init__(*args, **kwargs)

        # make sure, under no circumstances, computer is None
        assert self.user is not None

        mdat = get_mdat_customer_for_user(self.user)

        group_choices = list()
        group_selected = list()

        all_groups = directory_backend_get_groups(mdat.id)

        for group in all_groups:
            group_choices.append(
                ("group_" + group["guid"], _("Group") + ": " + group["name"])
            )
            if group["dn"].upper() in (
                dn.upper() for dn in self.computer_attributes["memberOf"]
            ):
                group_selected.append("group_" + group["guid"])

        self.fields["groups"].choices = group_choices
        self.fields["groups"].initial = group_selected


class DirectoryUserProfileInformation(UserKwargModelFormMixin, forms.Form):
    userprincipalname = forms.CharField(
        label=_("Username"),
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Username",
                "readonly": "true",
            }
        ),
        required=False,
    )
    displayname = forms.CharField(
        label=_("Full Name"),
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Full Name",

django_cloud_panel_directory/templates/django_cloud_panel_directory/list_computers.html
{% extends 'django_template_limitless/base.html' %}
{% load static %}
{% load i18n %}

{% block customcss %}
{% endblock %}

{% block customjs %}
    <script src="{% static "global_assets/js/main/jquery.min.js" %}"></script>
    <script src="{% static "global_assets/js/plugins/tables/datatables/datatables.min.js" %}"></script>

    <script type="text/javascript" class="init">
        $(document).ready(function () {
            $('#all_computers').DataTable({
                pageLength: 10,
                order: [[0, "asc"]]
            });
        });

        $(document).on('hidden', "#modal-content", function(){
            $("#modal-content").removeData("modal-content");
        });

        $(document).on('click', "a[data-toggle=modal]", function(){
            var target = $(this).attr("href");

            $.get(target, function(data){
                $("#modal-content").html(data);
                $("#modal-content").modal("show");
            });

            return false;
        });
    </script>
{% endblock %}

{% block heading-elements %}
    <br>
    <a href="/directory/computers/create" class="btn bg-blue float-right mx-1" data-toggle="modal" data-target="#modal">{% trans "New Computer" %}</a>
    <br><br><br>
{% endblock %}

{% block content %}
    <div class="card card-body shadow-lg">
        <table id="all_computers" class="table table-striped table-bordered nowrap">
            <thead>
            <tr>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Operating System" %}</th>
                <th>{% trans "SID" %}</th>
                <th>{% trans "Groups" %}</th>
                <th>{% trans "Join-Script" %}</th>
                <th>{% trans "Edit" %}</th>
                <th>{% trans "Delete" %}</th>
            </tr>
            </thead>
            <tbody>
            {% for computer in all_computers %}
                <tr>
                    <td>{{ computer.name.0 }}</td>
                    <td>{{ computer.operatingSystem.0 }} - {{ computer.operatingSystemVersion.0 }}</td>
                    <td>{{ computer.X_SID }}</td>
                    <td><a href="/directory/computer/{{ computer.X_GUID }}/groups" data-toggle="modal"
                           data-target="#modal"><i class="icon-address-book"></i></a></td>
                    <td><a href="/directory/computer/{{ computer.X_GUID }}/join-script" data-toggle="modal"
                           data-target="#modal"><i class="icon-download4"></i></a></td>
                    <td><a href="/directory/computer/{{ computer.X_GUID }}"><i class="icon-database-edit2"></i></a></td>
                    <td><a href="/directory/computer/{{ computer.X_GUID }}/delete" data-toggle="modal"
                           data-target="#modal"><i class="icon-trash"></i></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div id="modal-content" class="modal-content">
            </div>
        </div>
    </div>
{% endblock %}

django_cloud_panel_directory/templates/django_cloud_panel_directory/list_contacts.html
{% extends 'django_template_limitless/base.html' %}
{% load static %}
{% load i18n %}

{% block customcss %}
{% endblock %}

{% block customjs %}
    <script src="{% static "global_assets/js/main/jquery.min.js" %}"></script>
    <script src="{% static "global_assets/js/plugins/tables/datatables/datatables.min.js" %}"></script>

    <script type="text/javascript" class="init">
        $(document).ready(function () {
            $('#all_contacts').DataTable({
                pageLength: 10,
                order: [[0, "asc"]]
            });
        });

        $(document).on('hidden', "#modal-content", function(){
            $("#modal-content").removeData("modal-content");
        });

        $(document).on('click', "a[data-toggle=modal]", function(){
            var target = $(this).attr("href");

            $.get(target, function(data){
                $("#modal-content").html(data);
                $("#modal-content").modal("show");
            });

            return false;
        });
    </script>
{% endblock %}

{% block heading-elements %}
{% endblock %}

{% block content %}
    <div class="card card-body shadow-lg">
        <table id="all_contacts" class="table table-striped table-bordered nowrap">
            <thead>
            <tr>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Email" %}</th>
                <th>{% trans "Phonenumber" %}</th>
                <th>{% trans "Address" %}</th>
                <th>{% trans "Company" %}</th>
                <th>{% trans "Edit" %}</th>
                <th>{% trans "Delete" %}</th>
            </tr>
            </thead>
            <tbody>
            {% for contact in all_contacts %}
                <tr>
                    <td>{{ contact.name.0 }}</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><a href="#"><i class="icon-database-edit2"></i></a></td>
                    <td><a href="#" data-toggle="modal" data-target="#modal"><i class="icon-trash"></i></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div id="modal-content" class="modal-content">
            </div>
        </div>
    </div>
{% endblock %}

django_cloud_panel_directory/templates/django_cloud_panel_directory/list_realms.html
{% extends 'django_template_limitless/base.html' %}
{% load static %}
{% load i18n %}

{% block customcss %}
{% endblock %}

{% block customjs %}
    <script src="{% static "global_assets/js/main/jquery.min.js" %}"></script>
    <script src="{% static "global_assets/js/plugins/tables/datatables/datatables.min.js" %}"></script>

    <script type="text/javascript" class="init">
        $(document).ready(function () {
            $('#all_realms').DataTable({
                pageLength: 10,
                order: [[1, "asc"]]
            });
        });
        $(document).on('hidden', "#modal-content", function(){
            $("#modal-content").removeData("modal-content");
        });

        $(document).on('click', "a[data-toggle=modal]", function(){
            var target = $(this).attr("href");

            $.get(target, function(data){
                $("#modal-content").html(data);
                $("#modal-content").modal("show");
            });

            return false;
        });
    </script>
{% endblock %}

{% block heading-elements %}
{% endblock %}

{% block content %}
    <div class="card shadow-lg">
        <div class="card-header">
            <br>
            <h2 style="color:red">{% trans "BETA FEATURE" %}</h2>
            <p style="color:red">
                {% trans "During the BETA phase, realms can only be managed by the support staff." %}<br>
                {% trans "Please contact the customer support if you like to change settings." %}
            </p>
            <hr>
        </div>
        <div class="card-body">
            <table id="all_realms" class="table table-striped table-bordered nowrap">
                <thead>
                <tr>
                    <th>{% trans "ID" %}</th>
                    <th>{% trans "Domain" %}</th>
                    <th>{% trans "Domain Type" %}</th>
                    <th>{% trans "Is Default" %}</th>
                    <th>{% trans "Edit" %}</th>
                    <th>{% trans "Delete" %}</th>
                </tr>
                </thead>
                <tbody>
                {% for realm in all_realms %}
                    <tr>
                        <td>{{ realm.domainID }}</td>
                        <td>{{ realm.domain }}</td>
                        <td>{{ realm.domainType }}</td>
                        <td>{{ realm.isDefault }}</td>
                        <td><a href="/directory/realm/{{ realm.domain }}"><i class="icon-database-edit2"></i></a></td>
                        <td><a href="/directory/realm/{{ realm.domain }}/delete" data-toggle="modal"
                               data-target="#modal"><i
                                class="icon-trash"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div id="modal-content" class="modal-content">
            </div>
        </div>
    </div>
{% endblock %}

django_cloud_panel_directory/templates/django_cloud_panel_directory/modal_change_profile_picture.html
{% extends 'django_template_limitless/minimal_skeleton_with_css_js.html' %}
{% load static %}
{% load i18n %}


{% block customjs %}
    <script src="{% static "global_assets/js/main/jquery.min.js" %}"></script>
    <script src="{% static "global_assets/js/plugins/media/cropper.min.js" %}"></script>
    <script type="text/javascript" class="init">
        $("#modal-continue").on("click", function () {
            document.getElementById("post-img").value = document.getElementById("image_result").cropper.getCroppedCanvas().toDataURL();
            $("#api-form").submit();
        });

        $('.container > img').cropper({
            aspectRatio: 1,
            zoomable: false,
            cropBoxResizable: false,
        });

        upload = document.querySelector('#file-input')
        upload.addEventListener('change', (e) => {
            if (e.target.files.length) {
                // start file reader
                const reader = new FileReader();
                reader.onload = (e) => {
                    if (e.target.result) {
                        document.getElementById("image_result").src = e.target.result
                        document.getElementById("image_result").cropper.replace(e.target.result)
                    }
                };
                reader.readAsDataURL(e.target.files[0]);
            }
        });
    </script>
{% endblock %}

{% block content %}
    <!-- Modal -->
    <div class="modal-header">
        <h5 class="modal-title" id="modal-title">{{ content_title_main }} - {{ content_title_sub }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <form action="/directory/user_account/settings/change-profile-picture" method="post" id="api-form" enctype="multipart/form-data">{% csrf_token %}
            <input type="hidden" id="post-img">
        </form>
        <!-- Basic markup -->
        <div class="container mt-4" style="height: 500px">
            <img id="image_result" class="cropped" src="{{ image_path }}">
        </div>
        <div class="box">
            <input type="file" id="file-input">
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Close" %}</button>
        <button id="modal-continue" type="button" class="btn btn-primary">{% trans "Create" %}</button>
    </div>
{% endblock %}

django_cloud_panel_directory/templates/django_cloud_panel_directory/modal_computer_delete.html
{% extends 'django_template_limitless/minimal_skeleton_with_css_js.html' %}
{% load static %}
{% load i18n %}

{% block customjs %}
    <script type="text/javascript" class="init">
        $("#modal-save").on("click", function () {
            $("#api-form").submit();
        });

        // Countdown
        var timeout = 5

        function countDown() {
            if (timeout == 0) {
                clearInterval(delete_timer)
                document.getElementById("modal-continue").disabled = false;
            } else {
                timeout--;
                document.getElementById("p_countdown").innerHTML = "Please wait " + timeout + " seconds before continuing.";
            }
        }

        var delete_timer = setInterval('countDown()', 1000);

    </script>
{% endblock %}

{% block content %}
    <!-- Modal -->
    <div class="modal-header">
        <h5 class="modal-title" id="modal-title">{{ content_title_main }} - {{ content_title_sub }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <h1 style="color:red;">{% translate "Data Loss Warning!" %}</h1>
        <ul>
            <li>{% translate "All data linked to this computer will be erased." %}</li>
            <li>{% translate "If the system has not been decommissioned yet, it might result in undefined behavior." %}</li>
            <li>{% translate "This action can not be reversed, deletion is permanent." %}</li>
        </ul>
        <p id="p_countdown">{% translate "Please wait 5 seconds before continuing." %}</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button id="modal-continue" type="button" class="btn btn-primary" disabled>Continue</button>
    </div>
{% endblock %}

django_cloud_panel_directory/templates/django_cloud_panel_directory/modal_computer_join_script.html
{% extends 'django_template_limitless/minimal_skeleton_with_css_js.html' %}
{% load static %}
{% load i18n %}

{% block customjs %}
    <script type="text/javascript" class="init">
        $("#modal-continue").on("click", function () {
            $("#api-form").submit();
        });

        // Countdown
        var timeout = 5

        function countDown() {
            if (timeout == 0) {
                clearInterval(join_timer)
                document.getElementById("modal-continue").disabled = false;
            } else {
                timeout--;
                document.getElementById("p_countdown").innerHTML = "Please wait " + timeout + " seconds before continuing.";
            }
        }

        var join_timer = setInterval('countDown()', 1000);

    </script>
{% endblock %}

{% block content %}
    <!-- Modal -->
    <div class="modal-header">
        <h5 class="modal-title" id="modal-title">{{ content_title_main }} - {{ content_title_sub }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <h1 style="color:red;">{% translate "Data Loss Warning!" %}</h1>
        <ul>
            <li>{% translate "Requesting the executable will change the computer password and thus invalidate trust." %}</li>
            <li>{% translate "Requesting the executable while the computer is already joined, it might result in undefined behavior." %}</li>
            <li>{% translate "Never use the same executable again, it is meant to be run only once per request." %}</li>
            <li>{% translate "This executable is meant to be run on a new client / server." %}</li>
        </ul>
        <p id="p_countdown">{% translate "Please wait 5 seconds before continuing." %}</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button id="modal-continue" type="button" class="btn btn-primary" disabled>Continue</button>
    </div>
{% endblock %}

django_cloud_panel_directory/templates/django_cloud_panel_directory/modal_computers_create.html
{% extends 'django_template_limitless/minimal_skeleton_with_css_js.html' %}
{% load static %}
{% load i18n %}


{% block customjs %}
    <script type="text/javascript" class="init">
        $("#modal-continue").on("click", function () {
            $("#api-form").submit();
        });
    </script>
{% endblock %}

{% block content %}
    <!-- Modal -->
    <div class="modal-header">
        <h5 class="modal-title" id="modal-title">{{ content_title_main }} - {{ content_title_sub }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <form action="{% url 'modal_computers_create' %}" method="post" id="api-form">
            {% csrf_token %}
            <table>
                {{ directory_create_computer_form.as_table }}
            </table>
        </form>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Close" %}</button>
        <button id="modal-continue" type="button" class="btn btn-primary">{% trans "Create" %}</button>
    </div>
{% endblock %}

django_cloud_panel_directory/templates/django_cloud_panel_directory/modal_group_manage_members.html
{% extends 'django_template_limitless/minimal_skeleton_with_css_js.html' %}
{% load static %}
{% load i18n %}

{% block customcss %}
    <link href="{% static "multi-select/css/multi-select.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block customjs %}
    <script src="{% static "multi-select/js/jquery.multi-select.js" %}"></script>

    <script type="text/javascript" class="init">
        $("#modal-continue").on("click", function () {
            $("#api-form").submit();
        });
        $(document).ready(function () {
            $('#id_members').multiSelect();
        });
    </script>
{% endblock %}

{% block content %}
    <!-- Modal -->
    <div class="modal-header">
        <h5 class="modal-title" id="modal-title">{{ content_title_main }} - {{ content_title_sub }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <form action="{{ request.path }}" method="post" id="api-form">
            {% csrf_token %}
            <table>
                {{ group_members_form }}
            </table>
        </form>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Close" %}</button>
        <button id="modal-continue" type="button" class="btn btn-primary">{% trans "Save" %}</button>
    </div>
{% endblock %}